---
# tasks file for sysdev.openshift

- name: download and untar openshift
  unarchive:
    src: "https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-server-v3.10.0-dd10d17-linux-64bit.tar.gz"
    copy: no
    dest: "/tmp"
- name: move openshift to usr/local/sbin
  shell: mv o* k* h* t* /usr/local/sbin
  args:
    chdir: /tmp/openshift-origin-server-v3.10.0-dd10d17-linux-64bit
- name: get public ip address
  shell: curl ipecho.net/plain
  register:  ip_pub 
- name: copy and paste this message 
  debug: 
    msg: " sudo /usr/local/sbin/oc cluster up --public-hostname={{ ip_pub.stdout }} --host-data-dir=/home/{{ lookup('env','USER') }}/opens_data "

